### ISSUE TITLE
Error after selecting the drop down of saved outfits

### ISSUE THREAD

**Issue by Dizzard92** [WoW-MogIt/MogIt_SetTransmog#1]
Received the following after selecting the drop down of saved outfits at the transmogrifier 

Message: Interface\AddOns\MogIt_SetTransmog\Core.lua:180: attempt to index local 'outfit' (a number value)
Time: Fri Jul 22 18:30:05 2022
Count: 2
Stack: Interface\AddOns\MogIt_SetTransmog\Core.lua:180: attempt to index local 'outfit' (a number value)
[string "=[C]"]: ?
[string "@Interface\AddOns\MogIt_SetTransmog\Core.lua"]:180: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:1075: in function <Interface\SharedXML\UIDropDownMenu.lua:933>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Interface\AddOns\MogIt\Libs\Libra\Dropdown.lua"]:79: in function `Toggle'
[string "@Interface\AddOns\MogIt_SetTransmog\Core.lua"]:244: in function <Interface\AddOns\MogIt_SetTransmog\Core.lua:243>

Locals:

**Comment by Dizzard92** [comment]
Version 9.2.5
MogIt Version: 3.9.7
MogIt_SetTransmog Version: 1.5.4

**Comment by Wyr3d** [comment]
Yeah, it's wardrobe outfits - I'm assuming the link to the in-game transmog is broken.

In the meantime, you can save your wardrobe outfits to Mogit (you'd have to manually do so if you hven't already) and then remove them from the wardrobe. This will stop Mogit popping up the LUA errors, since there is no wardrobe outfits to try and load.

Not exactly a fix, but a decent enough band-aid for now. To delete outfits from the wardrobe, got to a transmog vendor,, and click the cog at the end of the outfit name, then confirm deletion. I wish they would do the same for Mogit, since a button is easier than trying to recall whatever button combo delete is. I'm pretty sure it was shift + left click, but this isn't working :/

**Comment by Lombra** [comment]
So, I have pushed a fix that should restore basic menu functionality. Because a number of other issues remain however, I will not be publishing a release at this time. You can grab `Core.lua` from this repository if you like.
